### ISSUE TITLE
Expose sort by field in query

### ISSUE THREAD

**Issue by taoshengshi** [RangerMauve/ipld-prolly-indexer#7]

**Comment by taoshengshi** [comment]
Query and sort by a field? @RangerMauve

**Comment by RangerMauve** [comment]
Yup, so right now we have a way to use indexes for searching for items that equal a specific value. A good extension from there would be to have `GreaterThan` and `LessThan` fields that work similar to `Equal` but do `>` and `<` comparisons.

As well there should be a way to specify a `Sort` field in the Query to choose which field to try to sorty by. Sorting is a bit tricky because you need the sorted field to be at the start of the index array. E.g. if you want to sort by `date` you need to have an index that looks like `['date','whateverElse']`. However when you have `Equals` fields they can come before the `sort` field since you can quickly seek to that type and skip others. e.g. an index that looks like `[type, date, somethingElse`]` could satisfy the queyy `{Equals: {type: "example"}, GreaterThan: {date: today}, Sort: "date"}`.

This is the approach I took in hyperbeedeebee and the algorithm for choosing the best index for a query can be found here: https://github.com/RangerMauve/hyperbeedeebee/blob/default/index.js#L315
